#Limit range example
apiVersion: v1 
kind: LimitRange 
metadata: 
  name: my-limits 
spec: 
  limits:
    type: Container 
    min: {cpu: "100m", memory: "100Mi"}
    max: {cpu: "400m", memory: "400Mi"}
    default: {cpu: "300m", memory: "312Mi"}

--- 
#Resource quota example 
apiVersion: v1
kind: ResourceQuota 
metadata:
  name: my-quota
spec: 
  hard: 
    requests.cpu: "10"
    requests.memory: 20Gi 
    limits.cpu: "20"
    limits.memory: 40Gi
    pods: "50"
