apiVersion: v1
kind: Pod
metadata:
  name: downward-api-volume
  labels:
    app: downward-test-pod
    environment: testing
  annotations:
    version: "v1.0"
spec:
  restartPolicy: Always
  containers:
  - name: metadata-container
    image: busybox
    imagePullPolicy: Always
    command: [ "/bin/sh", "-c", "cat /etc/podinfo/* && sleep 3600" ]
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
      limits:
        cpu: "200m"
        memory: "200Mi"
    volumeMounts:
    - name: downward-api-volume
      mountPath: /etc/podinfo

  volumes:
  - name: downward-api-volume
    downwardAPI:
      items:
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels

      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations
