apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod-2
  labels:
    environment: testing
  namespace: default
spec:
  nodeSelector:
    disk: ssd
  restartPolicy: Always
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /tmp/hostfile
      type: FileOrCreate
  containers:
  - name: busybox-pod
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      protocol: TCP
      name: http
    resources:
      requests:
        cpu: "0.1"
        memory: "10Mi"
      limits:
        cpu: "0.5"
        memory: "200Mi"
    env:
    - name: HOSTPATH_POD
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: HOSTPATH_POD_LABELS
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    command: [ "/bin/sh", "-c", "sleep 3600" ]
    volumeMounts:
    - name: hostpath-volume
      mountPath: /data
