apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: testing-pod
    environment: testing
spec:
  containers:
  - name: test-container
    image: nginx:latest
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    env:
    - name: DB_HOST
      value: "3306"
    resources:
      requests:
        cpu: "2"
        memory: "10Mi"
      limits:
        cpu: "4"
        memory: "20Mi"
