apiVersion: v1 
kind: ReplicationController 
metadata:
  name: nginx-rc 
  labels: 
    app: nginx-rc
    environment: testing 
spec:
  replicas: 3
  selector: 
    name: test-pod 
  template: 
    metadata: 
      labels: 
        name: test-pod 
    spec: 
      containers:
        - name: nginx-rc
          image: nginx:latest 
          ports: 
            - containerPort: 80 
              name: http 
              protocol: TCP 
          env: 
            - name: db_host 
              value: "4000"
          resources: 
            requests: 
              cpu: "2"
              memory: "10Mi"
            limits: 
              cpu: "5"
              memory: "20Mi"
            
            

          