apiVersion: v1
kind: Namespace
metadata:
  name: kube-services
---

apiVersion: v1
kind: Service
metadata:
  name: clusterip-svc

spec:
  selector:
    app: nginx-app
  ports:
  - port: 3306
    targetPort: 3306

  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc

spec:
  selector:
    app: nginx-app
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30008

  type: NodePort
---

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc

spec:
  selector:
    app: nginx-app
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: externalname-svc
spec:
  type: ExternalName
  externalName: db.example.com
