apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: nginx-deploy 
  labels:
    app: nginx-app 
spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: my-app
  template: 
    metadata: 
      labels: 
        app: my-app 
    spec:
      containers: 
        - name: nginx-container 
          image: nginx:latest 
          imagePullPolicy: Always 
          command: ["/bin/sh", "-c", "echo 'Hello world'"]
          resources: 
            requests: 
              cpu: "2"
              memory: "100Mi"
            limits: 
              cpu: "4"
              memory: "200Mi"
      