apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-deploy 
  labels:
    app: app1 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: nginx-app 
  template: 
    metadata: 
      labels: 
        app: nginx-app 
    spec: 
      imagePullSecrets: 
        - name: regcred 
      containers: 
        - name: nginx-container 
          image: nginx:latest
          ports: 
            - containerPort: 80 
              name: http
              protocol: TCP 
          command: ["/bin/sh", "-c", "echo 'Hello world'"]
            