apiVersion: v1 
kind: Pod 
metadata: 
  name: test-pod 
  namespace: test 
  labels: 
    app: test-app 
    environment: testing 
spec: 
  securityContext: 
    runAsUser: 1000 
    runAsGroup: 1000
    runAsNonRoot: true 
    fsGroup: 2000
  containers: 
    - name: nginx-container 
      image: nginx:latest 
      imagePullPolicy: Always 
      resources: 
        requests: 
          cpu: "100m"
          memory: "512Mi"
      env: 
        - name: "SECURITY_TEST"
          value: "0"
      securityContext: 
        allowPrivilegeEscalation: false 
        readOnlyRootFilesystem: true 