apiVersion: v1 
kind: Pod 
metadata: 
  name: test-pod 
  namespace: kite 
  labels: 
    app: test-app 
    environment: testing 
spec: 
  volumes: 
    - name: writable-volume 
      emptyDir: {} 
  securityContext: 
    runAsUser: 1000 
    runAsGroup: 3000 
    fsGroup: 2000 
    runAsNonRoot: true 
  imagePullSecrets: 
    - name: regcred 
  containers: 
    - name: test-container 
      image: busybox:latest
      command: 
        - "sh"
        - "-c"
        - "sleep 3600"
      ports: 
        - containerPort: 8080 
          name: http 
          protocol: TCP 
      securityContext: 
        allowPrivilegeEscalation: false 
        readOnlyRootFilesystem: true 
      volumeMounts: 
        - name: writable-volume 
          mountPath: /writable