apiVersion: v1 
kind: Pod 
metadata: 
  name: test-pod 
  namespace: kite 
spec: 
  imagePullSecrets: 
    - name: regcred 
  securityContext: 
    runAsUser: 1000 
    runAsGroup: 3000 
    fsGroup: 2000 
    runAsNonRoot: true 
  containers: 
    - name: test-container 
      image: busybox:latest 
      command: ['sh', '-c', 'sleep 3600']
      securityContext: 
        allowPrivilegeEscalation: false 
        capabilities: 
          drop: 
            - ALL 
          add: 
            - NET_ADMIN 
            - SYS_TIME 
