apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deploy
  labels:
    environment: testing
spec:
  replicas: 2
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - frontend
      - backend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: secret-example
      containers:
      - name: nginx-container
        image: nginx:latest
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: secret-example
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-example
              key: DB_PASSWORD
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
