apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  labels:
    app: sidecar-testing
    environment: testing
spec:
  containers:
  - name: main-app
    image: nginx:latest
    ports:
    - containerPort: 80

    resources: 
      requests:
        cpu: "2"
        memory: "10Mi"

  - name: sidecar-logger
    image: curlimages/curl:latest
    command:
    - sh
    - -c
    - |
      while true; do 
        curl -s http://localhost:80 > /dev/null && echo 'Main app is healthy' || echo 'Main app is not healthy'
        sleep 5 
      done 
