apiVersion: v1 
kind: Pod 
metadata: 
  name: readiness-pod 
  labels: 
    app: readiness-pod-eg
    environment: testing 
spec: 
  volumes: 
    - name: nginx-volume 
      emptyDir: {} 
  containers: 
    - name: nginx-container 
      image: nginx:1.18 
      imagePullPolicy: Always 
      command: 
        - "sh"
        - "-c"
        - "sleep 60"
      readinessProbe: 
        httpGet: 
          path: /healthz 
          port: 8080 
        initialDelaySeconds: 60 
        periodSeconds: 10 
        timeoutSeconds: 15 
        successThreshold: 5 
        failureThreshold: 15 
        