apiVersion: v1
kind: Pod
metadata:
  name: probe-test-pod
  labels:
    app: probe-test
    environment: testing
spec:
  containers:
  - name: test-pod
    image: nginx:1.18
    imagePullPolicy: Always
    command:
    - sh
    - -c
    - |
      apt update && apt install -y netcat-openbsd && nc -l -p 9444 && sleep 3600
    startupProbe:
      tcpSocket:
        port: 9444
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3
        timeoutSeconds: 1
        failureThreshold: 1
